import { P10_TABLE, P8_TABLE } from "../config/constants.js";
import { permute } from "../utils/sdes_utils.js";

export class KeyGeneratorVisualizer {
    static generateKeys(masterKey) {
        let logs = [];
        
        // P10 Permutation
        let p10 = permute(masterKey, P10_TABLE);
        logs.push({ 
            title: "KEY GEN: P10", 
            val: p10, 
            desc: "10-bit Master Key is permuted using the P10 table." 
        });

        // Left Shift 1 (LS-1)
        let l = p10.substring(0, 5), r = p10.substring(5);
        l = l.substring(1) + l[0]; 
        r = r.substring(1) + r[0];
        logs.push({ 
            title: "KEY GEN: LS-1", 
            val: l + r, 
            desc: "Performed 1-bit left shift on both 5-bit halves." 
        });

        // K1 Generation (P8)
        let k1 = permute(l + r, P8_TABLE);
        logs.push({ 
            title: "KEY GEN: K1 RESULT", 
            val: k1, 
            desc: "Subkey K1 is generated by applying P8 permutation to the LS-1 output." 
        });

        // Left Shift 2 (LS-2)
        l = l.substring(2) + l.substring(0, 2); 
        r = r.substring(2) + r.substring(0, 2);
        logs.push({ 
            title: "KEY GEN: LS-2", 
            val: l + r, 
            desc: "Performed 2-bit circular left shift on the previous halves." 
        });

        // K2 Generation (P8)
        let k2 = permute(l + r, P8_TABLE);
        logs.push({ 
            title: "KEY GEN: K2 RESULT", 
            val: k2, 
            desc: "Subkey K2 is generated by applying P8 permutation to the LS-2 output." 
        });

        return { keys: { k1, k2 }, logs };
    }
}